### ISSUE TITLE
区块写错BUG20181212_ 微信木盈【bug】

### ISSUE THREAD

**Issue by ningzhelong** [UCHAIN-WORLD/uchain-fullnode#128] opened 2018-12-12 08:56 UTC
附件已发给永动机

**Comment by o-u-p** [comment] 2018-12-13 05:30
Since the problem cannot be reproduced, close it temporarily, if any question just reopen it @yuyuyu2018 .

**Comment by yuyuyu2018** [comment] 2018-12-14 03:50
Can not be reproduced, first closed

**Closed by yuyuyu2018** 2018-12-14 03:50 UTC
